audit_header: false
title: Greater Las Vegas Real Estate Video Blog with Michael Dedic
description: >-
  Our mission at The Dedic Team is to be your best resource for Greater Las
  Vegas real estate advice. Whether you are a buyer, seller, or investor, our
  team of professionals can answer any questions you might have about real
  estate. If you are looking to buy or sell a home, you can get all the
  information and the latest updates, tips, and tricks from The The Dedic Team,
  your professional Greater Las Vegas Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:
client:
  name: Michael Dedic
  title:
  license_number:
  about_markdown: >-
    Henderson Realtor who has also been a real estate investor for 17+ years in
    the Las Vegas Valley. Graduate in Finance from UNLV. You can find him, his
    wife Barbie, & Daughter at many of the fine Vegan, Yoga, & meditational
    events around town. Michael has also previously directed analysis for over
    $1 Billion in assets for almost a decade. His tenured experience in analysis
    and negotiation along with his care for his clients create a harmonic Real
    Estate experience.
  brand: Dedic Team
  brokerage: Signature Real Estate Group
  market: Greater Las Vegas
  address: '2200 Paseo Verde Pkwy Suite 300 Henderson, NV 89052'
  phone: 702-466-7118
  phone_type:
  phone2:
  phone2_type:
  email: sold@greaterlasvegashousesblog.com
  url: 'http://greaterlasvegashouses.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'https://www.greaterlasvegashouses.com/homevalue/default'
  second_CTA_text: Home Search
  second_CTA_URL: 'https://www.greaterlasvegashouses.com/'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: What’s Your Greater Las Vegas Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: 'https://www.greaterlasvegashouses.com/homevalue/default'
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: Looking for a Greater Las Vegas Home?
    CTA_text2: Search the entire MLS for your Greater Las Vegas home.
    CTA_link_text2: Search the MLS
    CTA_url2: 'https://www.greaterlasvegashouses.com/'
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:
socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/DedicTeam/?modal=admin_todo_tour
  linkedin_url: https://www.linkedin.com/in/mike-dedic-1a0a9922/
  youtube_url: https://www.youtube.com/channel/UCmFY5tA4x4rg77Uj5YUVB1A
  twitter_url:
  instagram_url: https://www.instagram.com/dedic_team/?hl=en
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: Greater Las Vegas Real Estate Podcast with Michael Dedic
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Greater
    Las Vegas Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from The Dedic Team - your professional
    Greater Las Vegas Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Greater Las
    Vegas, home selling tips, home for sale, home buying, home buying process,
    property finder, property search, property, real estate market, estate
    agent, realestate, real estate listings, buying a house, homes for sale,
    mls, home buyer
  author: Michael Dedic
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Greater Las Vegas Houses Video Blog
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg
site_colors:
  brand_color: '#e51515'
  theme_color: '#6d6d6d'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#000000'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'